### ISSUE TITLE
license violation

### ISSUE THREAD

**Issue by SaidBySolo** [Team-Reato/KRB-v2#3]
https://github.com/Team-Reato/KRB-v2/blob/master/OpenSource/SchoolBot-py_Remake.py

This source is under the MIT License.

Provide copyright holder and license.

**Comment by SaidBySolo** [comment]
I am the copyright owner of this source code and can provide the original source code upon request.

**Comment by KaRinKaRin876** [comment]
> I am the copyright owner of this source code and can provide the original source code upon request.

Currently KaRin Bot v2 is not executing the content (school information), and I will delete the file because it was used as a test when running Python.
I have not seen the license for the file, so I will be able to process the contents of the license violation as file deletion.
From now on, I will not violate the license when I bring the bot source code.

**Comment by KaRinKaRin876** [comment]
This issue will remain open until you agree to a license violation.

**Comment by SaidBySolo** [comment]
Has confirmed.

We will close the issue.
